---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-major]
    commit-message:
      # Prefix all commit messages
      prefix: defender-client-deps
    labels:
      - dependabot
      - dependencies
      - vulnerabilites
    # Allow up to 5 open pull requests
    open-pull-requests-limit: 5
