---
template: |
  ## Next Release Version: v$NEXT_MINOR_VERSION

  ## Changes
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_MINOR_VERSION

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: \<*_&
