---
minimum_pre_commit_version: 1.15.0
default_stages:
  - commit
  - push

repos:
  - repo: local
    hooks:
      - id: pre-commit
        name: Update pre-commit
        entry: pre-commit install --install-hooks -t pre-commit -t pre-push
        pass_filenames: false
        language: system
        files: ^\.pre-commit-config.yaml$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: forbid-new-submodules
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
        files: \.yaml$
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: fixtures/.*
  - repo: local
    hooks:
      - id: style-fixes
        name: Run lint & format with fixes
        exclude: (\.md|\.sh)$
        entry: yarn style
        language: system
