---
name: Pre-requisites
description: |
  Setup Pre-requisites

outputs:
  package-name: ${{ steps.provenance.package-name }}
  package-download-name: ${{ steps.provenance.package-download-name }}
  package-download-sha256: ${{ steps.provenance.package-download-sha256 }}
  provenance-name: ${{ steps.provenance.provenance-name }}
  provenance-download-name: ${{ steps.provenance.provenance-download-name }}
  provenance-download-sha256: ${{ steps.provenance.provenance-download-sha256 }}

runs:
  using: composite
  steps:
    - name: Use node@16
      uses: actions/setup-node@v3
      with:
        node-version: 16.20.0

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Node modules cache
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          ~/.cache/node-gyp-cache
        key: "${{ runner.os }}-yarn-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}"
        restore-keys: |
          ${{ runner.os }}-yarn-${{ env.cache-name }}-
      env:
        cache-name: v4

    - name: Build
      id: provenance
      uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v1.6.0
      with:
        run-scripts: "yarn --frozen-lockfile, yarn style, yarn build"
