name: ci

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  checks: write
  pull-requests: read
  id-token: write # For signing
  contents: read
  actions: read

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Build
      id: build
      uses: ./.github/actions/prepare

    - name: Get outputs
      run: |
        echo "package_name=${{ steps.build.outputs.package-name }}" >> $GITHUB_OUTPUT
        echo "package_download_name=${{ steps.build.outputs.package-download-name }}" >> $GITHUB_OUTPUT
        echo "package_download_sha256: ${{ steps.build.outputs.package-download-sha256 }}" >> $GITHUB_OUTPUT
        echo "provenance_name: ${{ steps.build.outputs.provenance-name }}" >> $GITHUB_OUTPUT
        echo "provenance_download_name: ${{ steps.build.outputs.provenance-download-name }}" >> $GITHUB_OUTPUT
        echo "provenance_download_sha256: ${{ steps.build.outputs.provenance-download-sha256 }}" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
    - name: Run tests
      run: yarn test
