name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3.5.2

    - name: Use node@16
      uses: actions/setup-node@v3
      with:
        node-version: 16.20.0

    - name: Node modules cache
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          ~/.cache/node-gyp-cache
        key: "${{ runner.os }}-yarn-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}"
        restore-keys: |
          ${{ runner.os }}-yarn-${{ env.cache-name }}-
      env:
        cache-name: v4

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Check build
      run: yarn build

    - name: Check linting
      run: yarn lint:check

  test:
    name: Unit Tests
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Use node@16
      uses: actions/setup-node@v3
      with:
        node-version: 16.20.0

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Node modules cache
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          ~/.cache/node-gyp-cache
        key: "${{ runner.os }}-yarn-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}"
        restore-keys: |
          ${{ runner.os }}-yarn-${{ env.cache-name }}-
      env:
        cache-name: v4

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Lint & format checks
      run: yarn style

    - name: Build
      run: yarn build

    - name: Run tests
      run: yarn test
