name: ci

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  checks: write
  pull-requests: read
  contents: write
  actions: read
  id-token: write

jobs:
  prepare:
    name: Prepare pre-requisites
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Prepare pre-requisites
      uses: ./.github/actions/prepare

  # Deterministic Build & tests
  provenance:
    needs: prepare
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v1.6.0
    with:
      run-scripts: "install-deps, nx-build-test-skip-cache"
      node-version: "16.20.0"
