name: ci

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  checks: write
  pull-requests: read
  contents: write
  actions: read
  id-token: write

jobs:
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v1.6.0
    with:
      run-scripts: "yarn --frozen-lockfile, yarn style, yarn build"
  test:
    needs: provenance
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Build
      id: build
      uses: ./.github/actions/prepare

    - name: Get outputs
      run: |
        echo "package_name=${{ needs.provenance.outputs.package-name }}" >> $GITHUB_OUTPUT
        echo "package_download_name=${{ needs.provenance.outputs.package-download-name }}" >> $GITHUB_OUTPUT
        echo "package_download_sha256: ${{ needs.provenance.outputs.package-download-sha256 }}" >> $GITHUB_OUTPUT
        echo "provenance_name: ${{ needs.provenance.outputs.provenance-name }}" >> $GITHUB_OUTPUT
        echo "provenance_download_name: ${{ needs.provenance.outputs.provenance-download-name }}" >> $GITHUB_OUTPUT
        echo "provenance_download_sha256: ${{ needs.provenance.outputs.provenance-download-sha256 }}" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
    - name: Run tests
      run: yarn test
