name: ci

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3.5.2

    - name: Prepare pre-requisites
      uses: ./.github/actions/prepare

    - name: Check linting
      run: yarn style

    - name: Check build
      run: yarn build

  test:
    name: Unit Tests
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Prepare pre-requisites
      uses: ./.github/actions/prepare

    - name: Run tests
      run: yarn test
